name = "StringCases"
uuid = "f22f4433-750e-5048-95f9-cae576f2c120"
authors = ["Dan Segal <dan@seg.al>", "Vincent Laugier <vincent.laugier@gmail.com>"]
version = "0.1.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
