include("camelcase.jl")
include("kebabcase.jl")
include("pascalcase.jl")
include("snakecase.jl")
include("spacecase.jl")

include("underscore.jl")
include("dasherize.jl")
include("capitalize.jl")
include("camelize.jl")
include("classify.jl")
